### ISSUE TITLE
Error: Insufficient Funds for Transfer

### ISSUE THREAD

**Issue by theonrex** [cyberconnecthq/cc-content-app#2]
## Issue description
 I encountered an error while trying to complete a blockchain transaction even though I had enough bnb testnet coin. I need assistance in resolving this error. 
The error message I received is as follows:

![Annotation 2023-02-11 234922](https://user-images.githubusercontent.com/91835162/218284443-929cf96c-8c1f-4d0b-9d0c-290d2b52fdd9.png)

I opened thee console and found this error

![Annotation 2023-02-12 000135](https://user-images.githubusercontent.com/91835162/218284732-a6a43ee8-b3a8-4894-abae-404d2d632a16.png)

``res 3000 
{__typename: 'RelayActionError', reason: 'insufficient funds for transfer', lastKnownTxHash: null}
lastKnownTxHash
: 
null
reason
: 
"insufficient funds for transfer"
__typename
: 
"RelayActionError"
[[Prototype]]
: 
Object``

Here is the website link: 
 https://cc-content-app.vercel.app/posts

**Comment by emersonliuuu** [comment]
Hi @theonrex ,
I've encountered same question and I believed their `Relayer`(who actually pay the transaction fee) have no test BNB token in the wallet, so that's why even you have enough funds but still not work.
You can clone this repo to local and setup your own `Relayer` [here](https://dashboard.cyberconnect.me/) (remember to add some funds to it).

**Comment by theonrex** [comment]
Thank you @emersonliuuu  for your response and for providing a solution to my issue. I have cloned the repo and set up my Relayer with some funds and that resolves the problem. I appreciate your help!
